// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL: Supabase direct connection (port 5432) — bypasses PgBouncer.
    // Required for Prisma Migrate since PgBouncer does not support migration commands.
    url: process.env["DIRECT_URL"],
  },
});
