service: poro-guess-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}

package:
  individually: false
  excludeDevDependencies: true
  patterns:
    - '!**'
    - 'dist/**'

    # Prisma
    - 'prisma/schema.prisma'
    - 'node_modules/.prisma/client/**'
    - 'node_modules/@prisma/client/**'
    
    # Node Modules without dev dependencies
    - 'node_modules/**'
    
    # Cut all dev dependencies modules
    - '!node_modules/typescript/**'
    - '!node_modules/@types/**'
    - '!node_modules/eslint/**'
    - '!node_modules/prettier/**'
    - '!node_modules/jest/**'
    - '!node_modules/.cache/**'

functions:
  main:
    handler: dist/src/main.handler
    timeout: 29
    memorySize: 512
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true
