const fs = require('fs');
const path = require('path');

const hintsMap = {
  "Aatrox": ["Originates from Shurima, now considered a Darkin", "Wields a massive, living greatsword", "Once an Ascended warrior, now trapped within his weapon", "Seeks to bring about the apocalypse to end his own suffering", "Known as the World Ender"],
  "Ahri": ["Vastayan from Ionia", "Uses spiritual magic and a specialized orb", "Has fox-like features, including nine tails", "Absorbs the memories and emotions of others", "A prominent member of the K/DA virtual music group"],
  "Akali": ["Hails from Ionia", "Wields a kama and a kunai", "Former member of the Kinkou Order", "Known as the Rogue Assassin", "Shrouds herself in a smoke screen during combat"],
  "Akshan": ["From Shurima", "Wields an ancient relic weapon called the Absolver", "A rogue Sentinel of Light", "Can revive fallen allies by killing their murderer", "Swings around the battlefield using a grappling hook"],
  "Alistar": ["A Minotaur from the Great Barrier", "Fights with his bare hands and immense physical strength", "Was forced into gladiatorial combat in Noxus", "Known for headbutting and pulverizing enemies", "You can't milk those!"],
  "Ambessa": ["A Noxian warlord and matriarch", "Mother to Medarda (Mel)", "Featured prominently in Arcane", "Rules through sheer strength and intimidation", "Uses heavy brute force and military tactics"],
  "Amumu": ["An ancient Shuriman mummy", "Uses his own bandages as weapons", "Cursed with eternal sadness and loneliness", "His tears can damage nearby enemies", "Always looking for a friend"],
  "Anivia": ["An ancient Freljordian demigod", "Embodies the power of ice and snow", "Takes the form of a massive crystalline phoenix", "Can be reborn from an egg upon death", "Creates an impassable wall of ice"],
  "Annie": ["From the lands around Noxus", "A child prodigy with immense pyromantic magic", "Carries a stuffed bear named Tibbers", "Summons her bear as a massive fiery beast", "Has you seen my bear Tibbers?"],
  "Aphelios": ["A Lunari assassin from Mount Targon", "Wields five different moonstone weapons", "Guided by the spirit of his sister, Alune", "Cannot speak due to drinking the poison of the noctum flower", "Has the most complex HUD in the game"],
  "Ashe": ["Iceborn Warmother of the Avarosan tribe in the Freljord", "Wields a bow of True Ice", "Seeks to unite the tribes of the Freljord", "Fires an enchanted crystal arrow that stuns from afar", "Married to Tryndamere (politically)"],
  "Aurelion Sol": ["A cosmic entity from the celestial realm", "Creates stars and breathes starfire", "Was tricked into servitude by the Aspects of Targon", "Also known as the Star Forger", "Can pull a massive star from the sky to crash into the battlefield"],
  "Aurora": ["A vastayan from the Freljord", "Travels between the mortal realm and the spirit realm", "Has rabbit-like features", "Helps lost spirits find their way", "Creates a massive spirit realm zone in combat"],
  "Azir": ["The ancient Emperor of Shurima", "An Ascended being representing a hawk/eagle", "Commands an army of sand soldiers", "Resurrected the Sun Disc", "Shurima! Your emperor has returned!"],
  "Bard": ["A celestial wanderer", "Collects magical chimes across the world", "Accompanied by small spirits called Meeps", "Can put everything in an area into stasis, including allies and towers", "Communicates only through chimes and musical notes"],
  "Bel'Veth": ["The Empress of the Void", "Created from a consumed city", "Takes the guise of a manta ray or a false human head", "Spawns endless Voidlings", "Consumes Void coral to gain true form"],
  "Blitzcrank": ["A giant steam golem from Zaun", "Created by Viktor (in original lore)", "Shoots his right hand out to grab enemies", "Can generate an EMP blast", "Fired up and ready to serve"],
  "Brand": ["A fiery spirit inhabiting a Freljordian body", "Wields explosive and burning pyromancy", "Was once an apprentice named Kegan Rodhe", "Leaves enemies ablaze, eventually exploding", "Ready to set the world on fire"],
  "Braum": ["A legendary hero of the Freljord", "Carries an enchanted, unbreakable vault door as a shield", "Accompanied by poros", "Known for his massive mustache and big heart", "Stand behind me!"],
  "Briar": ["A failed blood magic experiment from Noxus", "A vampire-like creature constrained by a pillory", "Goes into a blood frenzy that she cannot fully control", "Kicks and bites her way through enemies", "Created by the Black Rose"],
  "Caitlyn": ["The Sheriff of Piltover", "Wields a custom-built hextech sniper rifle", "Partnered with Vi to keep the peace", "Uses yordle snap traps", "Fires a targeted Ace in the Hole from extremely long range"],
  "Camille": ["The Principal Intelligencer of Clan Ferros in Piltover", "An augmented human with hextech-powered bladed legs", "Uses hookshots to attach to walls", "Traps enemies in a hexagonal ultimate arena", "Precision is the difference between a butcher and a surgeon"],
  "Cassiopeia": ["A Noxian noblewoman cursed in Shurima", "Transformed into a half-human, half-snake creature", "Sister to Katarina", "Uses poisons and venom", "Can turn enemies to stone with her gaze"],
  "Cho'Gath": ["A terrifying monster from the Void", "Grows larger in size by eating enemies", "Fires spikes and ruptures the ground", "Has a true damage bite", "Om nom nom nom"],
  "Corki": ["A Yordle from Bandle City/Piltover", "Flies a customized reconnaissance copter", "Drops bombs and uses a gatling gun", "Can pick up a 'Package' from base for a massive bombing run", "Whiskey Delta!"],
  "Darius": ["The Hand of Noxus", "Wields a massive, blood-soaked axe", "Leader of the Trifarix along with Swain and Faceless", "Executes enemies with his Noxian Guillotine", "Applies bleeding stacks to enemies"],
  "Diana": ["The Scorn of the Moon from Mount Targon", "Wields a crescent moon blade", "An Aspect of the Moon", "Once a member of the Solari before finding the Lunari truth", "Draws enemies in with moonlight"],
  "Draven": ["The Glorious Executioner of Noxus", "Brother to Darius", "Throws and catches spinning axes", "Loves the spotlight and his own name", "Welcome to the League of Draven!"],
  "Dr. Mundo": ["A madman from Zaun who thinks he is a doctor", "Throws infected cleavers", "Goes where he pleases", "Regenerates massive amounts of health", "Mundo!"],
  "Ekko": ["A genius from the streets of Zaun", "Wields a bat and uses a Z-Drive to manipulate time", "Leader of the Firelights (in Arcane)", "Can rewind his own timeline to heal and deal damage", "It's not how much time you have, it's how you use it"],
  "Elise": ["A Noxian noblewoman with ties to the Shadow Isles", "Can transform into a giant spider", "Worships the Spider God Vilemaw", "Uses spiderlings to attack and cocoon enemies", "Only the spider is safe in her web"],
  "Evelynn": ["A demon of agony", "Takes the form of a seductive human", "Stalks her prey while completely camouflaged", "Lures victims in before unleashing her spikes", "Thrives on the pain of others"],
  "Ezreal": ["A prodigal explorer from Piltover", "Wields an ancient Shuriman gauntlet", "Shoots mystic shots and can blink short distances", "Belongs in a museum", "Fires a massive energy barrage across the map"],
  "Fiddlesticks": ["An ancient, primordial demon of fear", "Takes the form of a terrifying scarecrow", "Mimics the voices of its victims", "Drains the life from those around it", "Summons a massive flock of crows when jumping from the shadows"],
  "Fiora": ["The Grand Duelist of Demacia", "Wields a rapier with unmatched fencing skill", "Head of House Laurent", "Strikes the vital points of her enemies", "I have no equal!"],
  "Fizz": ["An amphibious Yordle from Bilgewater", "Wields a seastone trident", "Can become untargetable by hopping on his pole", "Summons a massive shark from the depths", "Feeding time!"],
  "Galio": ["A colossal petricite colossus in Demacia", "Created to absorb anti-magic", "Awakens only when powerful magic is present", "Crashes down from the sky to protect allies", "A massive, friendly gargoyle"],
  "Gangplank": ["The former Reaver King of Bilgewater", "Wields a cutlass and a pistol", "Loves eating oranges to cure crowd control", "Sets up explosive powder kegs", "Calls down a global cannon barrage from his ship"],
  "Garen": ["The Might of Demacia", "Leader of the Dauntless Vanguard", "Brother to Lux", "Spins around with his massive broadsword", "Demacia!"],
  "Gnar": ["A prehistoric Yordle frozen in True Ice", "Wields a boomerang", "Transforms into a massive, enraged beast when angry", "Throws boulders and smashes enemies into walls", "Shugi Shugi Shugi!"],
  "Gragas": ["A massive, boisterous brewer", "Travels the Freljord looking for the perfect pint", "Uses a giant cask as a weapon", "Body slams enemies and tosses explosive barrels of grog", "If you're buying, I'm in!"],
  "Graves": ["A famous outlaw and mercenary from Bilgewater", "Wields a massive double-barreled shotgun called Destiny", "Partner in crime with Twisted Fate", "Throws smoke grenades", "Must reload after firing two shots"],
  "Gwen": ["A doll brought to life by magic", "Created by Isolde (Viego's wife)", "Wields giant, magical scissors", "Surrounds herself in hallowed mist", "Snip snip!"],
  "Hecarim": ["A spectral knight from the Shadow Isles", "A centaur-like amalgamation of man and beast", "Leads the Iron Order", "Gains damage based on his movement speed", "Summons ghostly riders in a terrifying charge"],
  "Heimerdinger": ["A brilliant Yordle scientist in Piltover", "Sets up automated H-28G Evolution Turrets", "Fires hextech micro-rockets", "Has a massive brain (literally)", "Indeed, a wise choice!"],
  "Hwei": ["A visionary painter from Ionia", "Wields a magical paintbrush", "Uses combinations of 3 subject palettes (Disaster, Serenity, Torment)", "His spells are created by pressing two buttons sequentially", "An artist of complex emotions"],
  "Illaoi": ["The Truth Bearer of Nagakabouros in Bilgewater", "Wields a massive golden idol", "Pulls the spirit out of her enemies", "Summons ghostly tentacles to slam the ground", "Tests the worth of her opponents"],
  "Irelia": ["The Blade Dancer of Ionia", "Controls flying blades telekinetically", "Fought against the Noxian invasion", "Dashes rapidly between marked targets", "Ionia calls!"],
  "Ivern": ["The Green Father", "Once a cruel Freljordian warrior, now a tree-like friend to the forest", "Cannot attack jungle monsters, but rather frees them", "Summons his rock-golem friend, Daisy", "Creates bushes out of nowhere"],
  "Janna": ["A spirit of the wind worshipped in Zaun", "Wields a staff and controls gales", "Protects allies with shields and healing winds", "Summons tornados to knock enemies airborne", "The tempest is at her command"],
  "Jarvan IV": ["The Crown Prince of Demacia", "Wields a massive extending lance", "Creates a cataclysmic crater to trap enemies", "Dashes by pulling himself to his standard flag", "For my father, the King!"],
  "Jax": ["The Grandmaster at Arms from Icathia", "Fights with a brass lamppost", "The last known weapon-master of his fallen nation", "Can dodge all basic attacks", "Imagine if I had a real weapon!"],
  "Jayce": ["The Defender of Tomorrow from Piltover", "Wields the Hextech Mercury Hammer", "Can switch his weapon between melee (hammer) and ranged (cannon) modes", "Fires a massive shock blast through an acceleration gate", "Rival to Viktor"],
  "Jhin": ["A psychopathic assassin from Ionia", "Obsessed with the number four and theatrical artistry", "Wields a hand cannon called Whisper", "His fourth shot is always a guaranteed critical hit", "Perfection isn't good enough"],
  "Jinx": ["A manic and impulsive criminal from Zaun", "Wields a minigun (Pow-Pow) and a rocket launcher (Fishbones)", "Sister to Vi", "Fires a massive Super Mega Death Rocket", "Gets extremely excited (speed boost) when she gets a takedown"],
  "Kai'Sa": ["Daughter of the Void (originally from Shurima)", "Wears a symbiotic Void carapace", "Daughter of Kassadin", "Evolves her abilities based on her stats", "Fires a barrage of Icathian Rain"],
  "Kalista": ["The Spear of Vengeance from the Shadow Isles", "A spectral entity that binds herself to an ally", "Hops every time she throws a spear", "Rips spears out of enemies to deal damage", "Throws her bound ally into the enemy team"],
  "Karma": ["The Enlightened One of Ionia", "The spiritual leader of her people", "Uses Mantra to empower her abilities", "Fires inner flame and shields allies", "Always seek the spirit"],
  "Karthus": ["The Deathsinger of the Shadow Isles", "An undead lich who embraces death", "Singing a requiem to damage all enemies on the map", "Continues to cast spells for a few seconds after dying", "Press R to secure kills"],
  "Kassadin": ["The Void Walker from Shurima", "An adventurer who survived the Void to save his daughter", "Father to Kai'Sa", "Can blink rapidly using Riftwalk", "Uses a Nether Blade"],
  "Katarina": ["The Sinister Blade of Noxus", "A deadly assassin and sister to Cassiopeia", "Throws and teleports to her daggers", "Spins rapidly, throwing daggers at all nearby enemies", "Resets her abilities upon getting a takedown"],
  "Kayle": ["The Righteous Aspect of Justice", "Sister to Morgana", "Ascends and gains new forms/power at levels 6, 11, and 16", "Wields a flaming sword and eventually fights at range", "Can make an ally completely invulnerable"],
  "Kayn": ["The Shadow Reaper from Ionia", "Wields a sentient Darkin scythe named Rhaast", "Can transform into either a Shadow Assassin or a Darkin Bruiser", "Walks through walls using Shadow Step", "Infests the body of his enemies"],
  "Kennen": ["A Yordle member of the Kinkou Order in Ionia", "Wields shurikens and uses lightning magic", "Moves with the speed of a lightning rush", "Summons a massive slicing maelstrom of electricity", "The eyes never lie"],
  "Kha'Zix": ["The Voidreaver", "An insectoid Void predator", "Evolves his abilities by consuming prey", "Deals extra damage to isolated targets", "Rival to Rengar"],
  "Kindred": ["The Eternal Hunters", "The personification of death (Lamb and Wolf)", "Marks enemies to hunt them for permanent stacks", "Creates a zone where no one can die", "Never one... without the other"],
  "Kled": ["The Cantankerous Cavalier of Noxus", "A crazy Yordle who rides a cowardly lizard named Skaarl", "Fights with a bear trap on a rope and a pocket pistol", "Charges into battle with a massive shield", "I am Kled! High Major Commodore of the First Legion Third Multiplication Double Admiral Artillery Vanguard Company!"],
  "Kog'Maw": ["The Mouth of the Abyss", "A void creature that constantly spits acid", "Can fire living artillery from extremely long range", "Explodes in a passive death streak when killed", "Looks like a cute but terrifying caterpillar"],
  "K'Sante": ["The Pride of Nazumah in Shurima", "Wields massive Ntofo weapons made from monster hide", "Can shatter his weapons to become a high-damage skirmisher", "Pushes enemies through walls with his ultimate", "A tank that turns into an assassin"],
  "LeBlanc": ["The Deceiver of Noxus", "Leader of the secret society known as the Black Rose", "Uses illusions and distortion magic", "Can mimic her own spells", "The classic smoke and mirrors assassin"],
  "Lee Sin": ["The Blind Monk of Ionia", "A martial arts master", "Uses sonic waves to locate and dash to enemies", "Can kick enemies away with Dragon's Rage (Insec kick)", "Blindness is no impairment against a smelly enemy"],
  "Leona": ["The Radiant Dawn of Mount Targon", "A Solari warrior wielding a shield and sword of sunlight", "Can lock down enemies with a barrage of stuns", "Calls down a solar flare from the sky", "Praise the sun!"],
  "Lillia": ["The Bashful Bloom from Ionia", "A magical faun (half-deer, half-human) who protects the dreaming tree", "Prances around the battlefield, gaining movement speed", "Can put the entire enemy team to sleep with a lullaby", "Eep!"],
  "Lissandra": ["The Ice Witch of the Freljord", "Leader of the Frostguard", "Secretly watches over the frozen Watchers", "Can entomb herself or an enemy in dark ice", "Uses an ice claw to teleport"],
  "Locke": ["A new Noxian/Arcane-related champion", "Known as a relentless tracker/fighter", "Recent addition to the League roster", "Fights with grim determination", "Survives against the odds"],
  "Lucian": ["The Purifier", "Wields twin relic stone pistols", "Fights against the Black Mist of the Shadow Isles", "Husband to Senna", "Fires a rapid barrage of bullets in his Culling"],
  "Lulu": ["The Fae Sorceress", "A Yordle accompanied by her faerie companion, Pix", "Can polymorph enemies into harmless critters", "Makes her allies grow to massive size (Wild Growth)", "That tasted purple!"],
  "Lux": ["The Lady of Luminosity from Demacia", "A light mage and sister to Garen", "Uses a wand to cast light-binding spells", "Fires a massive laser beam (Final Spark)", "Demacia! (with a rainbow)"],
  "Malphite": ["Shard of the Monolith", "A massive creature made of living stone", "Moves like a rock", "Charges headfirst to knock up the entire enemy team", "Rock solid"],
  "Malzahar": ["The Prophet of the Void", "A Shuriman seer corrupted by the Void", "Summons Voidlings to fight for him", "Suppresses a single target with a Nether Grasp", "Spreads Malefic Visions to enemies"],
  "Maokai": ["The Twisted Treant of the Shadow Isles", "A massive animated tree spirit", "Tosses saplings into bushes to explode on enemies", "Summons a massive wall of roots to bind foes", "Return to the forest!"],
  "Master Yi": ["The Wuju Bladesman from Ionia", "A samurai who moves faster than the eye can see", "Meditates to heal himself", "Becomes immune to slows in his Highlander form", "My blade is yours"],
  "Mel": ["A Medarda councilor of Piltover", "Prominent Arcane character who joins the game", "Known for her political cunning and golden armor", "Daughter of Ambessa", "Uses Hextech/Golden magic to support or control"],
  "Milio": ["The Gentle Flame from Ixtal", "A young boy who uses fire magic to heal and soothe", "Accompanied by his 'fuemigo' fire buddies", "Can cleanse crowd control from his entire team", "Kicks a fiery ball that bounces on enemies"],
  "Miss Fortune": ["The Bounty Hunter of Bilgewater", "Captain Sarah Fortune", "Wields twin flintlock pistols named Shock and Awe", "Fires a massive cone of bullets in her Bullet Time", "Fortune doesn't favor fools"],
  "Wukong": ["The Monkey King from Ionia", "Wields an extending magical staff", "Can create a decoy clone of himself", "Spins his staff to knock up enemies (Cyclone)", "Trained by Master Yi"],
  "Mordekaiser": ["The Iron Revenant", "A resurrected warlord from ancient times (Noxus region)", "Wields a massive mace called Nightfall", "Banishes a single enemy to the Death Realm for a 1v1", "Iron stands eternal"],
  "Morgana": ["The Fallen", "Sister to Kayle", "Bound her own wings to walk among mortals in Demacia", "Fires a Dark Binding that roots for an eternity", "Chains enemies in a Soul Shackles area"],
  "Naafiri": ["The Hound of a Hundred Bites", "A Darkin assassin trapped in a pack of Shuriman desert hounds", "Summons packmates to attack her target", "Dashes as a unified pack", "The desert knows no mercy"],
  "Nami": ["The Tidecaller of the Marai (oceans near Mount Targon)", "A vastayan mermaid", "Traps enemies in an aqua prison bubble", "Summons a massive tidal wave", "Controls the power of the seas"],
  "Nasus": ["The Curator of the Sands from Shurima", "An Ascended jackal-headed being", "Brother to Renekton", "Infinitely stacks damage on his Siphoning Strike by farming", "Withers his enemies to a crawl"],
  "Nautilus": ["The Titan of the Depths from Bilgewater", "A giant armored diver", "Wields a massive anchor to hook enemies", "Summons depth charges that track enemies", "Lost to the sea, now he drags others down"],
  "Neeko": ["The Curious Chameleon", "A vastayan from a lost tribe in Ixtal", "Can disguise herself as any allied champion, minion, or monster", "Fires a blooming seed explosion", "Sho'ma!"],
  "Nidalee": ["The Bestial Huntress from Ixtal", "Throws extremely long-range javelins", "Can transform into a cougar", "Lays down bush traps", "Raised by cougars in the jungle"],
  "Nilah": ["The Joy Unbound from Kathkan", "Wields a fluid, water-like whip (the formlash)", "Uses the power of the demon of joy, Ashlesh", "A melee ADC who shares experience with her support", "Dashes through enemies and pulls them in"],
  "Nocturne": ["The Eternal Nightmare", "A demonic entity formed in the spirit realm", "Leaves a duskbringer trail", "Plunges the entire map into darkness before dashing to a target", "Darkness!"],
  "Nunu & Willump": ["A Freljordian boy and his yeti companion", "Rolls a massive, growing snowball", "Eats minions and monsters for massive healing", "Channels a huge area-of-effect absolute zero explosion", "Every adventure is better with a friend"],
  "Olaf": ["The Berserker of the Freljord", "Wields twin axes that he throws and picks up", "Seeks a glorious death in battle", "Becomes completely immune to crowd control in his Ragnarok", "Leaves nothing but carnage"],
  "Orianna": ["The Lady of Clockwork from Piltover", "A mechanical girl made of gears and springs", "Controls a deadly, independent brass ball", "Unleashes a devastating Command: Shockwave", "We will kill your enemies, that will be fun"],
  "Ornn": ["The Fire below the Mountain in the Freljord", "A demigod of forging and craftsmanship", "Can upgrade mythic/legendary items for his team", "Can buy items without returning to base", "Summons a massive elemental ram"],
  "Pantheon": ["The Unbreakable Spear from Mount Targon", "A mortal named Atreus wielding the weapons of a dead Aspect", "Uses a spear and shield with absolute determination", "Leaps high into the air to crash down across the map", "Mantheon"],
  "Poppy": ["Keeper of the Hammer from Demacia", "A Yordle searching for the 'Hero of Demacia' (not realizing it's her)", "Wields a hammer larger than herself", "Can knock enemies miles away with her ultimate", "Stops dashes with her steadfast presence"],
  "Pyke": ["The Bloodharbor Ripper of Bilgewater", "An undead harpooner who crosses names off his list", "A support champion who acts like an assassin", "Executes low-health enemies with an X-shaped strike", "Shares kill gold with the last assisting ally"],
  "Qiyana": ["Empress of the Elements from Ixtal", "Wields an Ohmlatl ring blade", "Can draw elements from the river, brush, and terrain", "Creates explosive shockwaves along walls", "Royal, arrogant, and deadly"],
  "Quinn": ["Demacia's Wings", "A ranger accompanied by her eagle, Valor", "Can vault off enemies to keep distance", "Valor carries her across the map at high speeds", "Blinds enemies and marks them for extra damage"],
  "Rakan": ["The Charmer from Ionia", "A vastayan battle-dancer", "Partner and lover to Xayah", "Dashes gracefully to heal and shield allies", "Charms the entire enemy team with his quickness"],
  "Rammus": ["The Armordillo from Shurima", "A mysterious, spiked creature of few words", "Rolls into a high-speed Powerball", "Taunts enemies into attacking his spiked shell", "Ok."],
  "Rek'Sai": ["The Void Burrower", "A massive female Xer'Sai queen from the Shuriman deserts", "Travels underground through a network of tunnels", "Senses enemy movement via tremors while burrowed", "Lunges out of the ground to knock up prey"],
  "Rell": ["The Iron Maiden of Noxus", "A metal-mancerr created by the Black Rose", "Rides a horse made of ferromancy that transforms into heavy armor", "Shatters enemy shields and steals their resistances", "A rebellious teenager fighting her creators"],
  "Renata Glasc": ["The Chem-Baroness of Zaun", "Runs Glasc Industries", "Uses chemtech to revive allies momentarily (Bailout)", "Her ultimate forces enemies to attack each other (Hostile Takeover)", "Wealth is the ultimate power"],
  "Renekton": ["The Butcher of the Sands from Shurima", "An Ascended crocodile being driven mad", "Brother to Nasus", "Uses Fury to empower his slices and dices", "Trapped in the tomb with Xerath for centuries"],
  "Rengar": ["The Pridestalker from Ixtal", "A vastayan trophy hunter", "Leaps from bushes to assassinate targets", "Can turn invisible and track prey in the thrill of the hunt", "Rival to Kha'Zix"],
  "Riven": ["The Exile of Noxus", "Wields a broken runic blade", "Fled Noxus after the chemical bombing in Ionia", "Highly mobile, using Q to perform a three-part Broken Wings combo", "Reforms her blade for her ultimate"],
  "Rumble": ["The Mechanized Menace", "A Yordle from Bandle City/Zaun who pilots a junkyard mech", "Uses a flamethrower and harpoons", "Must manage his heat gauge to avoid overheating", "Drops a massive line of rockets (The Equalizer)"],
  "Ryze": ["The Rune Mage", "A wandering archmage collecting dangerous World Runes", "Blue skin, carries a massive scroll on his back", "Rapid-fire spells using Overload combos", "Can teleport his entire team via Realm Warp"],
  "Samira": ["The Desert Rose", "A Noxian mercenary originally from Shurima", "Fights with dual pistols and a sword", "Builds a style grade from E to S to unlock her ultimate", "Spins in a deadly Inferno Trigger (like a blender)"],
  "Sejuani": ["Fury of the North", "Iceborn Warmother of the Winter's Claw in the Freljord", "Rides a massive Drüvask boar named Bristle", "Freezes enemies solid with glacial bolas", "Uses a true-ice flail"],
  "Senna": ["The Redeemer", "A Sentinel of Light who was trapped in Thresh's lantern", "Wife to Lucian", "Wields a massive relic cannon", "Collects mist wraiths to infinitely scale her range and damage"],
  "Seraphine": ["The Starry-Eyed Songstress from Piltover/Zaun", "A pop star who hears the songs of souls", "Rides a hextech acoustic stage", "Every third basic ability echoes (casts twice)", "Charms enemies with a massive encore"],
  "Sett": ["The Boss of Ionia's fighting pits", "A half-vastayan, half-human brawler", "Absorbs damage into Grit to unleash a massive true-damage Haymaker", "Suplexes the enemy tank into their own team", "Fights for his momma"],
  "Shaco": ["The Demon Jester", "A terrifying magical marionette", "Can instantly blink and turn invisible (Deceive)", "Places Jack-in-the-Box traps that fear enemies", "Creates an explosive clone of himself"],
  "Shen": ["The Eye of Twilight from Ionia", "Leader of the Kinkou Order", "Uses a spirit blade to block attacks", "Can teleport to any ally across the map while shielding them", "Maintains the balance"],
  "Shyvana": ["The Half-Dragon of Demacia", "A magical creature loyal to Jarvan IV", "Fights as a human but generates fury", "Transforms into a massive fire-breathing dragon", "Leaves a trail of scorched earth"],
  "Singed": ["The Mad Chemist of Zaun", "A brilliant but unethical scientist", "Runs around leaving a trail of poisonous gas", "Fling enemies over his shoulder", "Don't chase him!"],
  "Sion": ["The Undead Juggernaut of Noxus", "A resurrected war hero who killed a Demacian king", "Charges his massive axe for a devastating smash", "Sprints across the map as an unstoppable train", "Reanimates upon death to punch enemies in a frenzy"],
  "Sivir": ["The Battle Mistress of Shurima", "A mercenary who is secretly a descendant of Azir", "Wields a massive crossblade that she throws like a boomerang", "Can use a spell shield to block abilities", "Grants massive movement speed to her team (On the Hunt)"],
  "Skarner": ["The Crystal Vanguard (now reimagined in Ixtal)", "An ancient brackern", "Drags enemies away using his massive stinger (Impale)", "Picks up and throws massive boulders", "The earth trembles!"],
  "Smolder": ["The Fiery Fledgling", "A young, adorable dragon living in Noxus", "Sneezes fire and flaps around", "Stacks his passive to execute enemies late game", "Calls his mom to rain fire from above"],
  "Sona": ["The Maven of the Strings from Demacia/Ionia", "A mute musician who communicates via telepathy", "Plays an ancient instrument called the etwahl", "Provides passive auras of healing, speed, and damage", "Forces enemies to dance with her Crescendo"],
  "Soraka": ["The Starchild of Mount Targon", "A celestial being who gave up her immortality to heal mortals", "Sacrifices her own health to heal allies", "Can silence enemies with an equinox zone", "Calls upon the stars to heal her entire team globally"],
  "Swain": ["The Noxian Grand General", "A visionary leader who made a pact with a demon of secrets", "Commands demonic ravens", "Transforms into a demonic flock to drain life from nearby enemies", "Leader of the Trifarix"],
  "Sylas": ["The Unshackled of Demacia", "A mage rebellion leader who was imprisoned for years", "Fights with heavy petricite chains", "Can steal the ultimate ability of any enemy champion", "Magic is not a crime!"],
  "Syndra": ["The Dark Sovereign of Ionia", "A mage who wields immense, uncontrolled power", "Manifests dark spheres of magical energy", "Can pick up and throw minions or her own spheres", "Unleashes all her spheres in a devastating Unleashed Power"],
  "Tahm Kench": ["The River King", "A demon of greed from the waterways of Bilgewater", "Looks like a massive catfish", "Licks enemies to apply stacks, then swallows them whole", "Can devour an ally to save them"],
  "Taliyah": ["The Stoneweaver of Shurima", "A young mage who controls earth and stone", "Rides a rock board to surf along walls", "Throws volley of rocks (Threaded Volley)", "Summons a massive Weaver's Wall to block the map"],
  "Talon": ["The Blade's Shadow of Noxus", "An assassin adopted by the Du Couteau family", "Parkours over any wall in the game", "Throws a volley of returning blades", "Becomes invisible and unleashes a ring of blades"],
  "Taric": ["The Shield of Valoran from Mount Targon", "A disgraced Demacian who became the Aspect of the Protector", "Wields a gem-studded mace", "Can link with an ally to duplicate his spells", "Calls down cosmic radiance to make his team invulnerable"],
  "Teemo": ["The Swift Scout of Bandle City", "A cute Yordle with a sadistic reputation", "Shoots blinding darts from his blowgun", "Can turn completely invisible while standing still", "Plants invisible, exploding, poisonous mushroom traps"],
  "Thresh": ["The Chain Warden of the Shadow Isles", "A sadistic specter who tortures souls", "Throws a hook (Death Sentence) to drag enemies", "Throws a lantern to pull allies to safety", "Creates a pentagon box of spectral walls"],
  "Tristana": ["The Yordle Gunner of Bandle City", "Wields a massive cannon named Boomer", "Jumps long distances (Rocket Jump) which resets on kills", "Places explosive charges on towers and enemies", "Shoots a massive cannonball to knock enemies back"],
  "Trundle": ["The Troll King of the Freljord", "Wields a massive club made of True Ice (Boneshiver)", "Creates a pillar of ice to block paths", "Steals the stats and size of an enemy tank (Subjugate)", "Time to troll!"],
  "Tryndamere": ["The Barbarian King of the Freljord", "Husband to Ashe", "Uses fury to increase his critical strike chance", "Spins with his massive sword", "Becomes literally unkillable for 5 seconds (Undying Rage)"],
  "Twisted Fate": ["The Card Master of Bilgewater", "A charming gambler and con artist", "Uses magical playing cards (Blue, Red, Gold)", "Can reveal all enemies on the map", "Teleports long distances via Destiny"],
  "Twitch": ["The Plague Rat of Zaun", "A giant, mutated sewer rat", "Turns invisible (camouflage) and sneaks up on victims", "Uses a crossbow that fires toxic bolts", "Fires piercing bolts from extreme range (Spray and Pray)"],
  "Udyr": ["The Spirit Walker of the Freljord", "Channels the spirits of Freljordian demigods (Bear, Ram, Boar, Phoenix)", "Has no ultimate ability, just four stances", "Can Awaken his stances for empowered effects", "A highly versatile melee fighter"],
  "Urgot": ["The Dreadnought of Zaun", "A former Noxian headsman turned cyborg crab-monster", "Has shotgun knees that fire when he turns", "Fires a chem-drill to reel enemies in", "Grinds low-health enemies in his stomach grinder (Fear Beyond Death)"],
  "Varus": ["The Arrow of Retribution", "A Darkin trapped in a bow, inhabiting two Ionian hunters", "Charges up a massive piercing arrow", "Applies blight stacks that deal percent-health damage", "Shoots a tendril of corruption that roots enemies"],
  "Vayne": ["The Night Hunter of Demacia", "A monster hunter obsessed with purging dark magic", "Wields a wrist-mounted crossbow and a heavy silver crossbow", "Tumbles to dodge attacks and goes invisible during her ultimate", "Pins enemies to walls with Condemn"],
  "Veigar": ["The Tiny Master of Evil", "A Yordle corrupted by Mordekaiser's magic", "Infinitely stacks ability power by killing minions", "Drops a massive cage of dark matter (Event Horizon)", "Fires a giant Primordial Burst that deletes squishies"],
  "Vel'Koz": ["The Eye of the Void", "A floating tentacle monster obsessed with learning", "Fires geometry-based plasma beams that split at an angle", "Deals true damage after analyzing his target", "Shoots a massive, sweeping laser beam (Life Form Disintegration Ray)"],
  "Vex": ["The Gloomist", "A depressing Yordle from the Shadow Isles", "Hates sunshine and happiness", "Uses her shadow to attack and fear enemies", "Fires a shadow missile and dashes to the target (Shadow Surge)"],
  "Vi": ["The Piltover Enforcer", "Sister to Jinx", "Wields massive Atlas Gauntlets", "Punches her way through anything", "Unstoppably charges and dunks a single target (Cease and Desist)"],
  "Viego": ["The Ruined King", "The cause of the Ruination of the Shadow Isles", "Wields the Blade of the Ruined King", "Possesses the bodies of enemies he kills, stealing their abilities", "Searching endlessly for his dead wife, Isolde"],
  "Viktor": ["The Machine Herald of Zaun", "A brilliant scientist who embraces the 'Glorious Evolution'", "Upgrades his hex-core to augment his abilities", "Fires a death ray that sweeps across the ground", "Summons a devastating chaos storm"],
  "Vladimir": ["The Crimson Reaper of Noxus", "An ancient blood mage", "Heals himself by draining the life of enemies", "Can sink into a pool of blood to become untargetable", "Infects an area with a Hemoplague that explodes for massive damage"],
  "Volibear": ["The Relentless Storm of the Freljord", "A massive, lightning-wielding bear demigod", "Brother to Ornn", "Bites enemies to heal himself", "Leaps into the air and disables enemy towers with his ultimate"],
  "Warwick": ["The Uncaged Wrath of Zaun", "A man mutated into a werewolf-like beast by Singed", "Can smell low-health enemies globally (Blood Hunt)", "Runs faster toward bleeding targets", "Leaps massive distances to suppress his prey"],
  "Xayah": ["The Rebel of Ionia", "A vastayan revolutionary", "Partner to Rakan", "Throws razor-sharp feathers that she can recall", "Leaps into the air, becoming untargetable, to rain down feathers"],
  "Xerath": ["The Magus Ascendant of Shurima", "An ancient being of pure arcane energy", "Betrayed Azir to steal the Ascension ritual", "Fires long-range energy blasts as an artillery mage", "Roots himself to fire a barrage of arcane mortar shots"],
  "Xin Zhao": ["The Seneschal of Demacia", "A fierce warrior who wields a spear", "A former gladiator in the Noxian fighting pits", "Charges at enemies with an Audacious Charge", "Sweeps his spear to knock away all but his challenged target"],
  "Yasuo": ["The Unforgiven of Ionia", "A wandering samurai accused of murdering his master", "Brother to Yone", "Wields wind magic and dashes through minions", "Blocks projectiles with a Wind Wall and ults knocked-up targets"],
  "Yone": ["The Unforgotten of Ionia", "Brother to Yasuo", "Returned from death after defeating an azakana", "Wields two swords: one steel, one demonic", "Leaves his physical body to attack in spirit form"],
  "Yorick": ["The Shepherd of Souls from the Shadow Isles", "A monk who carries a vial of holy water", "Summons Mist Walkers from graves", "Raises the Maiden of the Mist to fight alongside him", "A split-pushing menace"],
  "Yunara": ["A newer character added to the game", "Known for unique interactions", "An explorer or fighter type", "Brings fresh mechanics to the rift", "Often seen in recent Arcane/lore updates"],
  "Yuumi": ["The Magical Cat", "A familiar from Bandle City looking for her master, Norra", "Rides a magical floating book", "Attaches to an ally, becoming untargetable", "Fires a controllable prowling projectile"],
  "Zaahen": ["A mysterious figure from the latest updates", "Possesses unique combative abilities", "Fights with relentless energy", "Often associated with Zaun/Noxus lore", "Unleashes powerful bursts of damage"],
  "Zac": ["The Secret Weapon of Zaun", "A giant blob of green goo", "Stretches his arms to smash enemies together", "Charges up a massive elastic slingshot jump", "Splits into four blobs upon death, which can reform him"],
  "Zed": ["The Master of Shadows from Ionia", "Leader of the Order of Shadow", "Uses living shadows to mimic his attacks", "Places a Death Mark that pops for massive damage", "The unseen blade is the deadliest"],
  "Zeri": ["The Spark of Zaun", "A speedy ADC who shoots electric bursts", "Her auto-attack is a skillshot (Q ability)", "Grinds along walls", "Gains infinite movement speed during her Lightning Crash ultimate"],
  "Ziggs": ["The Hexplosives Expert", "A Yordle from Zaun who loves bombs", "Throws bouncing bombs", "Can destroy low-health towers instantly with his Satchel Charge", "Drops a massive Mega Inferno Bomb from afar"],
  "Zilean": ["The Chronokeeper of Icathia", "An ancient mage who controls time", "Throws time bombs that stick to targets", "Speeds up allies or severely slows enemies", "Can rewind time to resurrect a fallen ally (Chronoshift)"],
  "Zoe": ["The Aspect of Twilight", "A cosmic messenger who acts like a mischievous child", "Throws a Paddle Star that deals more damage the further it travels", "Can pick up dropped summoner spells and item actives", "Puts enemies to sleep from through walls"],
  "Zyra": ["Rise of the Thorns", "An ancient plant creature from Ixtal", "Spawns seeds that grow into spitters or lashers", "Roots enemies with grasping roots", "Summons a massive thicket that knocks up enemies"]
};

// Read current data
const dataPath = path.join(__dirname, '../prisma/champions-data.json');
const rawData = fs.readFileSync(dataPath, 'utf8');
const champions = JSON.parse(rawData);

// Update traits
let updatedCount = 0;
champions.forEach(champ => {
  if (hintsMap[champ.name]) {
    champ.traits = hintsMap[champ.name];
    updatedCount++;
  } else {
    // Fallback if missing
    champ.traits = [
      `Hint 1 for ${champ.name}`,
      `Hint 2 for ${champ.name}`,
      `Hint 3 for ${champ.name}`,
      `Hint 4 for ${champ.name}`,
      `Hint 5 for ${champ.name}`
    ];
  }
});

fs.writeFileSync(dataPath, JSON.stringify(champions, null, 2), 'utf8');
console.log(`Successfully updated ${updatedCount} champions with 5 hints.`);
